'''
All PySimpleGUI fonts (as far as i know)

By vapen_hem

GitHub: https://github.com/vapen-hem
Discord: Vapen_Hem#1161
YoutTube: https://www.youtube.com/channel/UCTHHIPTtETe6hawsfnZTM8A
'''
#PySimpleGUI library import
import PySimpleGUI as sg
#Window Theme
sg.theme("DarkTanBlue")
#Column Variable
col1=[
    [sg.Text("Arial",font=("Arial", 30))],
    [sg.Text("Arial Baltic",font=("Arial Baltic", 30))],
    [sg.Text("Arial Black",font=("Arial Black", 30))],
    [sg.Text("Arial CE",font=("Arial CE", 30))],
    [sg.Text("Arial CYR",font=("Arial CYR", 30))],
    [sg.Text("Arial Greek",font=("Arial Greek", 30))],
    [sg.Text("Arial TUR",font=("Arial TUR", 30))],
    [sg.Text("Bahnschrift",font=("Bahnschrift", 30))],
    [sg.Text("Bahnschrift Condensed",font=("Bahnschrift Condensed", 30))],
    [sg.Text("Bahnschrift Light",font=("Bahnschrift Light", 30))],
    [sg.Text("Bahnschrift Light Condensed",font=("Bahnschrift Light Condensed", 30))],
    [sg.Text("Bahnschrift Light SemiCondensed",font=("Bahnschrift Light SemiCondensed", 30))],
    [sg.Text("Bahnschrift SemiBold",font=("Bahnschrift SemiBold", 30))],
    [sg.Text("Bahnschrift SemiBold Condensed",font=("Bahnschrift SemiBold Condensed", 30))],
    [sg.Text("Bahnschrift SemiBold SemiConden",font=("Bahnschrift SemiBold SemiConden", 30))],
    [sg.Text("Bahnschrift SemiCondensed",font=("Bahnschrift SemiCondensed", 30))],
    [sg.Text("Bahnschrift SemiLight",font=("Bahnschrift SemiLight", 30))],
    [sg.Text("Bahnschrift SemiLight Condensed",font=("Bahnschrift SemiLight Condensed", 30))],
    [sg.Text("Bahnschrift SemiLight SemiConde",font=("Bahnschrift SemiLight SemiConde", 30))],
    [sg.Text("Bowlby One SC",font=("Bowlby One SC", 30))],
    [sg.Text("Bungee Inline",font=("Bungee Inline", 30))],
    [sg.Text("Cabin Sketch",font=("Cabin Sketch", 30))],
    [sg.Text("Calibri",font=("Calibri", 30))],
    [sg.Text("Calibri Light",font=("Calibri Light", 30))],
    [sg.Text("Cambria",font=("Cambria", 30))],
    [sg.Text("Cambria Math",font=("Cambria Math", 30))],
    [sg.Text("Candara",font=("Candara", 30))],
    [sg.Text("Candara Light",font=("Candara Light", 30))],
    [sg.Text("Cinzel Black",font=("Cinzel Black", 30))],
    [sg.Text("Comic Sans MS",font=("Comic Sans MS", 30))],
    [sg.Text("Consolas",font=("Consolas", 30))],
    [sg.Text("Constantia",font=("Constantia", 30))],
    [sg.Text("Cookie",font=("Cookie", 30))],
    [sg.Text("Corbel",font=("Corbel", 30))],
    [sg.Text("Corbel Light",font=("Corbel Light", 30))],
    [sg.Text("Courgette",font=("Courgette", 30))],
    [sg.Text("Courier",font=("Courier", 30))],
    [sg.Text("Courier New",font=("Courier New", 30))],
    [sg.Text("Courier New Baltic",font=("Courier New Baltic", 30))],
    [sg.Text("Courier New CE",font=("Courier New CE", 30))],
    [sg.Text("Courier New CYR",font=("Courier New CYR", 30))],
    [sg.Text("Courier New Greek",font=("Courier New Greek", 30))],
    [sg.Text("Courier New TUR",font=("Courier New TUR", 30))],
    [sg.Text("Doppio One",font=("Doppio One", 30))],
    [sg.Text("Ebrima",font=("Ebrima", 30))],
    [sg.Text("Euphorigenic",font=("Euphorigenic", 30))],
    [sg.Text("Fixedsys",font=("Fixedsys", 30))],
    [sg.Text("Franklin Gothic Medium",font=("Franklin Gothic Medium", 30))],
    [sg.Text("Fugaz One",font=("Fugaz One", 30))],
    [sg.Text("Gabriola Gadugi",font=("Gabriola Gadugi", 30))],
    [sg.Text("Georgia",font=("Georgia", 30))],
    [sg.Text("Great Vibes",font=("Great Vibes", 30))],
    [sg.Text("HoloLens MDL2 Assets",font=("HoloLens MDL2 Assets", 30))],
    [sg.Text("Impact",font=("Impact", 30))],
    [sg.Text("Ink Free",font=("Ink Free", 30))],
    [sg.Text("Inter",font=("Inter", 30))],
    [sg.Text("Javanese Text",font=("Javanese Text", 30))],
    [sg.Text("Kalam",font=("Kalam", 30))],
    [sg.Text("Kalam Light",font=("Kalam Light", 30))],
    [sg.Text("Leelawadee UI",font=("Leelawadee UI", 30))],
    [sg.Text("Leelawadee UI Semilight",font=("Leelawadee UI Semilight", 30))],
    [sg.Text("Lemon",font=("Lemon", 30))],
    [sg.Text("Limelight",font=("Limelight", 30))],
    [sg.Text("Lucida Console",font=("Lucida Console", 30))],
    [sg.Text("Lucida Sans Unicode",font=("Lucida Sans Unicode", 30))],
    [sg.Text("MS Gothic",font=("MS Gothic", 30))],
    [sg.Text("MS PGothic",font=("MS PGothic", 30))],
    [sg.Text("MS Sans Serif",font=("MS Sans Serif", 30))],
    [sg.Text("MS Serif",font=("MS Serif", 30))],
    [sg.Text("MS UI Gothic",font=("MS UI Gothic", 30))],
    [sg.Text("MV Boli",font=("MV Boli", 30))],
    [sg.Text("Malgun Gothic",font=("Malgun Gothic", 30))],
    [sg.Text("Malgun Gothic Semilight",font=("Malgun Gothic Semilight", 30))],
    [sg.Text("Marcellus SC",font=("Marcellus SC", 30))],
    [sg.Text("Marlett Megrim",font=("Marlett Megrim", 30))],
    [sg.Text("Microsoft Himalaya",font=("Microsoft Himalaya", 30))],
    [sg.Text("Microsoft JhengHei",font=("Microsoft JhengHei", 30))],
    [sg.Text("Microsoft JhengHei Light",font=("Microsoft JhengHei Light", 30))],
    [sg.Text("Microsoft JhengHei UI",font=("Microsoft JhengHei UI", 30))],
    [sg.Text("Microsoft JhengHei UI Light",font=("Microsoft JhengHei UI Light", 30))],
    [sg.Text("Microsoft New Tai Lue",font=("Microsoft New Tai Lue", 30))],
    [sg.Text("Microsoft PhagsPa",font=("Microsoft PhagsPa", 30))],
    [sg.Text("Microsoft Sans Serif",font=("Microsoft Sans Serif", 30))],
    [sg.Text("Microsoft Tai Le",font=("Microsoft Tai Le", 30))],
    [sg.Text("Microsoft YaHei",font=("Microsoft YaHei", 30))],
    [sg.Text("Microsoft YaHei Light",font=("Microsoft YaHei Light", 30))],
    [sg.Text("Microsoft YaHei UI",font=("Microsoft YaHei UI", 30))],
    [sg.Text("Microsoft YaHei UI Light",font=("Microsoft YaHei UI Light", 30))],
    [sg.Text("Microsoft Yi Baiti",font=("Microsoft Yi Baiti", 30))],
    [sg.Text("MingLiU-ExtB",font=("MingLiU-ExtB", 30))],
    [sg.Text("MingLiU_HKSCS-ExtB Modern",font=("MingLiU_HKSCS-ExtB Modern", 30))],
    [sg.Text("Mongolian Baiti",font=("Mongolian Baiti", 30))],
    [sg.Text("Montserrat Subrayada",font=("Montserrat Subrayada", 30))],
    [sg.Text("Myanmar Text",font=("Myanmar Text", 30))],
    [sg.Text("NSimSun",font=("NSimSun", 30))],
    [sg.Text("Nirmala UI",font=("Nirmala UI", 30))],
    [sg.Text("Nirmala UI Semilight",font=("Nirmala UI Semilight", 30))],
    [sg.Text("Noto Sans",font=("Noto Sans", 30))],
    [sg.Text("Orbitron",font=("Orbitron", 30))],
    [sg.Text("PMingLiU-ExtB",font=("PMingLiU-ExtB", 30))],
    [sg.Text("Palatino Linotype",font=("Palatino Linotype", 30))],
    [sg.Text("Permanent Marker",font=("Permanent Marker", 30))],
    [sg.Text("Playball",font=("Playball", 30))],
    [sg.Text("Quicksand",font=("Quicksand", 30))],
    [sg.Text("Quicksand Light",font=("Quicksand Light", 30))],
    [sg.Text("Quicksand Medium",font=("Quicksand Medium", 30))],
    [sg.Text("Roman",font=("Roman", 30))],
    [sg.Text("Russo One",font=("Russo One", 30))],
    [sg.Text("Script",font=("Script", 30))],
    [sg.Text("Segoe MDL2 Assets",font=("Segoe MDL2 Assets", 30))],
    [sg.Text("Segoe Print",font=("Segoe Print", 30))],
    [sg.Text("Segoe Script",font=("Segoe Script", 30))],
    [sg.Text("Segoe UI",font=("Segoe UI", 30))],
    [sg.Text("Segoe UI Black",font=("Segoe UI Black", 30))],
    [sg.Text("Segoe UI Emoji",font=("Segoe UI Emoji", 30))],
    [sg.Text("Segoe UI Historic",font=("Segoe UI Historic", 30))],
    [sg.Text("Segoe UI Light",font=("Segoe UI Light", 30))],
    [sg.Text("Segoe UI Semibold",font=("Segoe UI Semibold", 30))],
    [sg.Text("Segoe UI Semilight",font=("Segoe UI Semilight", 30))],
    [sg.Text("Segoe UI Symbol",font=("Segoe UI Symbol", 30))],
    [sg.Text("Shrikhand",font=("Shrikhand", 30))],
    [sg.Text("Sigmar One",font=("Sigmar One", 30))],
    [sg.Text("SimSun SimSun-ExtB",font=("SimSun SimSun-ExtB", 30))],
    [sg.Text("Sitka Banner",font=("Sitka Banner", 30))],
    [sg.Text("Sitka Display",font=("Sitka Display", 30))],
    [sg.Text("Sitka Heading",font=("Sitka Heading", 30))],
    [sg.Text("Sitka Small",font=("Sitka Small", 30))],
    [sg.Text("Sitka Subheading",font=("Sitka Subheading", 30))],
    [sg.Text("Sitka Text",font=("Sitka Text", 30))],
    [sg.Text("Small Fonts",font=("Small Fonts", 30))],
    [sg.Text("Sylfaen",font=("Sylfaen", 30))],
    [sg.Text("Symbol",font=("Symbol", 30)), sg.Text("(Symbol)")],
    [sg.Text("System",font=("System", 30))],
    [sg.Text("Tahoma",font=("Tahoma", 30))],
    [sg.Text("Teko SemiBold",font=("Teko SemiBold", 30))],
    [sg.Text("Terminal",font=("Terminal", 30))],
    [sg.Text("Times New Roman",font=("Times New Roman", 30))],
    [sg.Text("Times New Roman Baltic",font=("Times New Roman Baltic", 30))],
    [sg.Text("Times New Roman CE",font=("Times New Roman CE", 30))],
    [sg.Text("Times New Roman CYR",font=("Times New Roman CYR", 30))],
    [sg.Text("Times New Roman Greek",font=("Times New Roman Greek", 30))],
    [sg.Text("Times New Roman TUR",font=("Times New Roman TUR", 30))],
    [sg.Text("Trebuchet MS",font=("Trebuchet MS", 30))],
    [sg.Text("Ubuntu Mono",font=("Ubuntu Mono", 30))],
    [sg.Text("Verdana",font=("Verdana", 30))],
    [sg.Text("Webdings",font=("Webdings", 30)), sg.Text("(Webdings)")],
    [sg.Text("Wingdings",font=("Wingdings", 30)), sg.Text("(Wingdings)")],
    [sg.Text("Yellowtail",font=("Yellowtail", 30))],
    [sg.Text("Yu Gothic",font=("Yu Gothic", 30))],
    [sg.Text("Yu Gothic Light",font=("Yu Gothic Light", 30))],
    [sg.Text("Yu Gothic Medium",font=("Yu Gothic Medium", 30))],
    [sg.Text("Yu Gothic UI",font=("Yu Gothic UI", 30))],
    [sg.Text("Yu Gothic UI Light",font=("Yu Gothic UI Light", 30))],
    [sg.Text("Yu Gothic UI Semibold",font=("Yu Gothic UI Semibold", 30))],
    [sg.Text("Yu Gothic UI Semilight",font=("Yu Gothic UI Semilight", 30))],
    [sg.Text("qtquickcontrols",font=("qtquickcontrols", 30))],]

#Layout
layout = [[sg.Column(col1, element_justification='c', scrollable=True, vertical_scroll_only=True)]]

#Window
window =sg.Window("Column and Frame",layout, size=(610, 720))

#Event loop
while True:
    event, values = window.read()
    if event == sg.WIN_CLOSED or event == 'Cancel':
        break

#Window Close
window.close()
